#!/bin/sh

case $1 in
    "-s")
        xwallpaper --no-randr --tile ~/rules/wall
        ;;

    *)
        image_path=$(realpath "$1")
        if [ -f "$image_path" ]; then
            xwallpaper --no-randr --tile "$image_path"
            ln -sf "$image_path" ~/rules/wall
        fi
        ;;
esac

