#!/bin/sh

case $1 in
    "-s")
	display \
    	-page 3200x \
    	-sample 3200x \
    	-window root \
	~/rules/wall
        ;;

    *)
        image_path=$(realpath "$1")
        if [ -f "$image_path" ]; then
	display \
    	-page 3200x \
    	-sample 3200x \
    	-window root \
	"$image_path"
            ln -sf "$image_path" ~/rules/wall
        fi
        ;;
esac

