#!/bin/sh

efibootmgr -b 0000 -B
efibootmgr -b 0001 -B
efibootmgr -b 0002 -B

mkdir -p /boot/efi/linux
cp -f arch/x86/boot/bzImage /boot/efi/linux/bzImage.efi 

efibootmgr --create \
    --disk /dev/sda \
    --part 1 \
    --label "Linux" \
    --loader "\efi\linux\bzImage.efi" -u "root=/dev/sda2"
