#!/bin/sh

    while read -r line; do
        case $line in
            "real mem"*)
                mem=${line##*\(}
                mem=${mem%\)*}
                mem=${mem%%B}
				;;
        esac
    done < /var/run/dmesg.boot

    while read -r _ _ line _; do
        mem_used=${line}
    done <<-EOF 
    $(vmstat) 
EOF
    echo "$mem_used"/"$mem"
