#!/bin/sh
#
# Simple script to toggle github remote to git

repo_remote="$(git remote get-url origin || exit 1)"

case $repo_remote in
    *https*github*)
        repo=${repo_remote##https://github.com/}
        repo=${repo%%.git}
        repo=git@github.com:$repo.git
        echo 'signing key changed'
        git config user.signingkey C7509FB0D2DE4B09
        git config user.email 82726847+xeinye@users.noreply.github.com
        git config user.name xeinye
;;
	*git://git.zepp.club*)
        repo=${repo_remote##git://git.zepp.club/}
        repo=${repo%%.git}
        repo=git@git.zepp.club:${repo##*/}
    ;;

    *) exit 1 ;;
esac

printf 'Changing repo to %s\n' "$repo"
git remote set-url origin "$repo"

