#!/bin/sh -e

case $1 in
	post-build)
        case $2 in
            kiss) ;;
            *)
                rm -fr \
                    "$3/etc/bash_completions.d" \
                    "$3/usr/lib/charset.alias" \
                    "$3/usr/share/applications" \
                    "$3/usr/share/bash-completion" \
                    "$3/usr/share/doc" \
                    "$3/usr/share/fish" \
                    "$3/usr/share/gettext" \
                    "$3/usr/share/gtk-doc" \
                    "$3/usr/share/icons" \
                    "$3/usr/share/info" \
                    "$3/usr/share/locale" \
                    "$3/usr/share/man" \
                    "$3/usr/share/polkit-1" \
                    "$3/usr/share/sounds" \
                    "$3/usr/share/zsh"
            ;;
        esac
    ;;
esac
