#!/bin/sh
#
# Simple script to download, convert to flac and attach the thumbnail

yt-dlp \
    -x \
    --write-thumbnail  \
    --audio-format mp3 \
    --add-metadata \
    --parse-metadata ":(?P<meta_synopsis>)" \
    --parse-metadata ":(?P<meta_comment>)" \
    --parse-metadata ":(?P<meta_description>)" \
    --parse-metadata ":(?P<meta_purl>)" \
    --parse-metadata ":(?P<meta_date>)" \
    --metadata-from-title '%(artist)s - %(title)s' \
    -o '%(title)s.%(ext)s' \
    "$@" 

for f in *.webp ;do
mv -- "$f" "${f%.webp}.thumb"
done

rm Album*

# Crop the edges and resize
 mogrify \
    -fuzz 10% \
    -trim  \
    +repage \
    -format jpg \
    "*.thumb"

for file in *.mp3; 
do
   echo "${file%.*}.jpg" 
   mv "${file}" "${file%.*}.mus"
   ffmpeg -y -hide_banner -loglevel error -i "${file%.*}.mus" -i "${file%.*}.jpg" -map 0 -map 1 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" "${file%.*}.mp3"; 
done 

# Automatically organize music by artist/album.
for file in *.mp3;
do
    album=$(ffprobe -v error -print_format flat -show_format "$file" | sed -nE 's/format.tags.album="(.+)"/\1/p')
    artist=$(ffprobe -v error -print_format flat -show_format "$file" | sed -nE 's/format.tags.artist="(.+)"/\1/p')
    mkdir -p "$artist"/"$album"
    mv "$file" "$artist"/"$album"
done

rm ./*.mus ./*.jpg ./*.webp ./*.thumb 2>/dev/null
