#!/bin/sh
      
swidth=$(wattr w `lsw -r`)
geom="${swidth}x20"

BG="#202a31"
FG="#abb0c0"

LEMON_FLAVOR="-dbg $geom -B${BG} -F${FG}"

workspaces(){
    printf '%%{R} %s %%{R}' "$(cat /tmp/workspaces/curr)"
}

winname() {
    xprop -id "$(pfw)" | grep WM_CLASS | cut -d '"' -f 2
}


clock() {
	printf 'TIME %%{R} %s %%{R}' "$(date +%H:%M)"
}

bat(){
    case $(uname -s) in
        "Linux")
            printf 'BAT %%{R} %s %%{R}' "$(cat /sys/class/power_supply/BAT1/capacity)%"
            ;;

        "OpenBSD")
    esac
}


 todo() {
	printf 'TODO %%{R} %d %%{R}' $(<$HOME/rules/todo wc -l)
}


sound() {
    case $(uname -s) in
        "Linux")
            ;;

        "OpenBSD")
            sndioctl output.level | awk -F '=' '{ printf "%.2f%%\n", $2 * 100 }'
    esac
}

while :; do
	BUF=
	BUF="$(workspaces)"
    BUF="${BUF} %{c}$(winname)"
	BUF="${BUF}%{r}$(todo) $(sound) $(clock) $(bat)"
	echo $BUF
	sleep 1
done | lemonbar $LEMON_FLAVOR
