#!/bin/sh

mkdir -p "$HOME/med"

case "$@" in
    "-s") 
        import -window root "$HOME"/med/full-"$(date +%Y-%m-%d-%S)".png
        ;;
    *)
        import png:"$HOME"/med/ss.png 
        xclip  -t 'image/png' -selection 'clipboard' -i "$HOME"/med/ss.png
        mv "$HOME"/med/ss.png "$HOME"/med/"$(date +%Y-%m-%d-%S)".png 
        ;;
esac
