#!/bin/sh
#
echo "ssh key"
doas chown $USER ~/.ssh 
#echo "gpg"
#doas chown $USER ~/PRIVATE.GPG

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
#gpg --import ~/PRIVATE.GPG
#gpg --edit-key xein@zepp.club 
